version: '3'

volumes:
   dbdata:

services:
    db:
        image: mcmoe/mssqldocker:v2017.CU12.1
        container_name: database_postcomment
        environment:
          ACCEPT_EULA: Y
          SA_PASSWORD: 1p@sswordY
          MSSQL_DB: postcommentdb
          MSSQL_USER: postcommentdb_app
          MSSQL_PASSWORD: 1p@sswordY


    postcomment.api:
        container_name: api_postcomment
        depends_on:
           - db
        image: postcomment.api
        build:
          context: .
        ports:
          - "8080:80"
        environment:
          - ASPNETCORE_ENVIRONMENT=staging
        