apiVersion: apps/v1
kind: Deployment
metadata:
  name: postcommentapi
spec:
  selector:
    matchLabels:
      app: postcommentapi
  template:
    metadata:
      labels:
        app: postcommentapi
    spec:
      containers:
      - name: postcommentapi
        image: shivaspk/postcommentapi:1.0
        env:
        - name: sqlconnection__connectionString
          value: Server=postcommentdb;Database=postcommentdb;User=sa;Password=1p@sswordY;
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: postcomment
spec:
  type: NodePort
  selector:
    app: postcommentapi
  ports:
  - port: 80
    targetPort: 80

